/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#021945",
        "on-tertiary-container": "#ffc6b2",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#415382",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#344573",
        "secondary-container": "#b6c8fe",
        "tertiary-fixed-dim": "#ffb59b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#0052cc",
        "surface-container": "#eceef0",
        "tertiary-container": "#a33500",
        "on-surface": "#191c1e",
        "on-primary-container": "#c4d2ff",
        "inverse-primary": "#b2c5ff",
        "background": "#f7f9fb",
        "on-primary-fixed": "#001848",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2ff",
        "on-background": "#191c1e",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#812800",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "secondary": "#4c5d8d",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dae2ff",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#380d00",
        "tertiary-fixed": "#ffdbcf",
        "surface": "#f7f9fb",
        "tertiary": "#7b2600",
        "surface-tint": "#0c56d0",
        "secondary-fixed-dim": "#b4c5fb",
        "primary": "#003d9b",
        "on-surface-variant": "#434654"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
